### ISSUE TITLE
Setup server for deployment

### ISSUE THREAD

**Issue by BitFis** [BigSisl/xml-wgcard#1]
- [ ] Run the application on a server
additional
- [ ] CI / CD

**Comment by mogria** [comment]
- [ ] install fop and generate the letters

**Comment by BitFis** [comment]
deplozed at http://wgcard.zuercher.io (auto deployment added and reset daily 01:00)

**Comment by mogria** [comment]
well sorry to reopen this, but when i open it in firefox it blocks the loading of the xsl stylesheet because of the Content Security Policy
![image](https://user-images.githubusercontent.com/754512/54448236-8621eb80-474b-11e9-83d5-dbcb2fa1ae55.png)

**Comment by mogria** [comment]
I also see you run the internal php development webserver which might be problematic and doesn't allow setting such headers for files as far as i know... :/
