### ISSUE TITLE
Show list of promotions on home page

### ISSUE THREAD

**Issue by BitFis** [BigSisl/xml-wgcard#2]
- [x] Show the list of promotions on the homepage
- [ ] Make the promotions view more appealing to the user (design)
- [ ] Create a menu or add footer with links to the other subpages
  - [ ] register wg - needs a big button in header
  - [ ] promtions management and show wg list in the menu or in the footer of the page

**Comment by mogria** [comment]
an idea would be to add support for an image, but that is effort and may or may not be that simple with our current JSON implementation

**Comment by BitFis** [comment]
lets first finish every feature we have promised to fullfil, but here would be the issue #10

-

**Comment by mogria** [comment]
sure

**Comment by mogria** [comment]
The promotions are now shown on the start page
