### ISSUE TITLE
Use to generate a nice factsheet from the markdown

### ISSUE THREAD

**Issue by mogria** [BigSisl/xml-wgcard#8]
I have a nice script which can generate a two column layout for the factsheet using pandoc and xelatex.

Would that suffice? What do you think how we should do it?

**Comment by mogria** [comment]
[WGCard_Factsheet.pdf](https://github.com/BigSisl/xml-wgcard/files/2972157/WGCard_Factsheet.pdf)

**Comment by mogria** [comment]
This is how it looks as of the last commit

**Comment by mogria** [comment]
with the two column layout we save space and it makes it easier to embed images, because we can't scale them or float them using markdown

**Comment by mogria** [comment]
Although this might be problematic if we plan on doing a big Architecture Diagram (#4) we might have to use a seperate page for this and merge the pdfs?

**Comment by BitFis** [comment]
https://github.com/BigSisl/xml-wgcard/blob/master/WGCard_Factsheet.pdf
